config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :event, only: [:show, :new, :create, :index]
  resources :user, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
   after_create :participant_send

     def participant_send
         AttendanceMailer.welcome_participant(self).deliver_now
     end

end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :users, through: :attendances

#   validates :start_date, presence: true
#   validates :start_date, if: :in_the_past?
    
#   validates :duration, presence: true
#   validates :duration, if: :multiple_of_5?

#   validates :title, presence: true
#   validates :title, length: { in: 5..140 }

#   validates :description, presence: true
#   validates :description, length: { in: 20..1000 }

#   validates :price, presence: true
#   validates :price, length: { in: 1..1000 }
   
#   validates :location, presence: true
      
#   def in_the_past?
#     time = Time.now
#     if self.start_date < time
#       errors.add(:base,  "Date de debut erroné")
#       false
#     end
#     true
#  end

#  def multiple_of_5?
#     res = self.duration % 5
#     if res.positive?
#       errors.add(:base, 'erreur date de durée')
#       false
#     end

#     if self.negative?
#        errors.add(:base, 'erreur durée negative')
#        false
#     end
#     true
#  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :attendances
    has_many :events, through: :attendances

    after_create :welcome_send

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end
  
  def index
    @events = Event.all
  end

  def show
    @even = gossip_finder
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show

    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
<h1>Les Évenements</h1>
</div>

 <div class="jumbotron text-center">
  <% @events.each do |event| %>
      <div class="card-body">
      <h5 class="card-title text-center"> <%= event.title %> </h5>
      <a href="<%= event_path(event.id) %>" class="btn btn-primary text-center"> en savoir plus </a>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= %>">Veuillez créer un évènement</a>
      </li>
    </ul>
    <div class="btn-group dropleft">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    En savoir plus...
  </button>
  <div class="dropdown-menu">
    <% if !user_signed_in? %>
      <p class="dropdown-item"> <%= link_to "S'inscrire", new_user_registration_path %></p>
      <p class="dropdown-item"> <%= link_to "Se connecter", new_user_session_path %></p>
    <% else %>
    <p class="dropdown-item"> <%= link_to "Voir profil", user_path%></p>
      <p class="dropdown-item"> <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></p>
    <% end %>
  </div>
</div>
    </div>
  </nav>
    <%= yield %>
  </body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>